[tool.poetry]
name = "Coffee-Chatbot"
version = "1.1.0"
description = ""
authors = ["EvanCope"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
